package strategy;

import generator.Generator;
import observer.ObserverGeneratorAsync;

/**
 * Represents the sequential coherence in strategy
 * All observers read all values generated by the Generator at same time
 */
public class Sequential implements DiffusionStrategy {

    private Generator generator;

    @Override
    public void configure(Generator generator) {
        this.generator = generator;
    }

    @Override
    public void run() {
        this.generator.generateValue();
        for(ObserverGeneratorAsync<Generator> observerAsync:this.generator.getObserversAsync()) {
            observerAsync.update(this.generator);
        }
    }
}
