package chanel;

import generator.Generator;
import generator.GeneratorImpl;

import java.util.concurrent.Callable;
import java.util.concurrent.ScheduledExecutorService;

/**
 * Represents Method Invocation of Genetor getValue method
 *
 * */
public class GetValue implements Callable<Integer> {

    ScheduledExecutorService scheduled;
    private Generator generator;

    public GetValue(Generator generator) {
        this.generator = generator;
    }

    /**
     * Value generated by Generator
     * @return value of generator method
     * */
    private Integer getValue(){
        return this.generator.getValue();
    }

    public Integer call() throws Exception {
        return getValue();
    }
}

